spring:
  datasource:
    url: jdbc:postgresql://peanut.db.elephantsql.com:5432/dzoiwbfo
    username: dzoiwbfo
    password: kDLA5mMqSH_6rOG8QuFPRwKULhEDezK0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="anjkp40c" password="WujqAqNOgQkuEV1RkRaiNeKvtlPWTuW1";
    consumer:
      group-id: anjkp40c-consumers
    topic:
      article: anjkp40c-article
cloudinary:
  name: dsn9vablo
  key: 387541922456337
  secret: vaTmn3aGLMifZzAllcZsoIurQVc
