spring:
  datasource:
    url: jdbc:postgresql://ec2-3-218-171-44.compute-1.amazonaws.com:5432/d7epg75am28quf
    username: bdghqzwhutprxp
    password: 5880b578fff1bf25343e9ee4631023096c9859c00c6b8d54acffd7e691b808c8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  kafka:
    bootstrap-servers: tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094
    topic: w9dl6gl3-article
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="w9dl6gl3" password="0hKSsGSaPEDM7thw5hRayEWp33JWTcTY";
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: w9dl6gl3-consumers
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: com.eden.gallery.message
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
cloudinary:
  name: htfvhf91n
  key: 931965461199396
  secret: ZQn2S87oD1Nd9DIgHSv6PKUhuIo
